server:
   port: 6007
   
eureka:
   instance:
      hostname: eureka2
   client:
      register-with-eureka: false   #false不向注册中心注册自己
      fetch-registry: false         #false标识自己就是注册中心，不需要和client端一样检索服务
      service-url:
         #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/   #查询服务和注册服务的地址
         defaultZone: http://eureka1:6006/eureka/,http://eureka3:6008/eureka/