server:
   port: 8001

mybatis:
   config-location: classpath:mybatis/mybatis.cfg.xml
   type-aliases-package: com.sunsy.springcloud.entity
   mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
   application:
      name: microservicecloud-dept
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cloudDb01
      username: root
      password: 413531
          
eureka:
   client:
      service-url:
         #defaultZone: http://192.168.44.63:6006/eureka
         defaultZone: http://eureka1:6006/eureka,http://eureka2:6007/eureka,http://eureka3:6008/eureka
   instance:
      instance-id: dept-provider-8001
      prefer-ip-address: true
      